### ISSUE TITLE
in train_model_combined.py scaled

### ISSUE THREAD

**Issue by Songminkee** [epiception/CalibNet#12]
at line 43~44
fx_scaled = 2*(fx)/np.float32(IMG_WDT)              # focal length x scaled for -1 to 1 range
fy_scaled = 2*(fy)/np.float32(IMG_HT)               # focal length y scaled for -1 to 1 range

i think.....
if  fx,fy= 7.215377e+02, IMG_HT = 375,	IMG_WDT = 1242
fx_scaled = 1.1619
fy_scaled = 3.8482

I think the range of focal length is not -1 to 1.
can you help me?

and
at line 45~46
cx_scaled = -1 + 2*(cx - 1.0)/np.float32(IMG_WDT)   # optical center x scaled for -1 to 1 range
cy_scaled = -1 + 2*(cy - 1.0)/np.float32(IMG_HT)    # optical center y scaled for -1 to 1 range

Why are you subtracting 1? (cx - 1.0)&(cy - 1.0)

**Comment by HeyNuts** [comment]
if scale to 0-1, then new_fx = fx/width. now it is -1 ~1 ,then 2* fx / width
cx  cy is centered at (0,0) pixel on image , so new_cx = { [1-(-1)]/1 } * (cx / width)  +  (-1 - 0)

you can first consider the case when scaling to 0~1. And then add scale and offset to it.
