### ISSUE TITLE
Duplicate mapping

### ISSUE THREAD

**Issue by KleinYuan** [epiception/CalibNet#14]
Amazing works on CalibNet!

I have one question after reading through the paper and code:

Even though you avoid the duplication in bilinear sampling layer, in [this step](https://github.com/epiception/CalibNet/blob/master/code/common/all_transformer.py#L91-L96), the duplicates could still happen, correct?

Would be interested to know your feedback.

**Comment by epiception** [comment]
Thanks!
Yes, multiple points in 3D could project to the same index on the image plane.

**Comment by KleinYuan** [comment]
Appreciate for your quick response.

@epiception sorry, one more follow up question:

I see you mentioned in your paper that your transformer implementation was extended from original Torch GVNN. What's the main difference that you have changed? Or they are identical?
