### ISSUE TITLE
Cannot create parsed_set.txt because it cannot find angle_list.txt

### ISSUE THREAD

**Issue by sreenjoy-daimler** [epiception/CalibNet#18]
Hi, I'm attempting to create the _parsed_set.tx_t file. I have downloaded the dataset using the _dataset_builder_parallel.sh_ but when I run the _parser.py_ script in the location of the dataset, this is what it complains about. Any advice?

![Screenshot from 2019-07-03 16-57-40](https://user-images.githubusercontent.com/52507326/60631503-8d314000-9db4-11e9-8ac0-2ec100c3aa58.png)

**Comment by epiception** [comment]
Seems like angle_list.txt was not created or saved in some other location. You could change the path in line 181 of dataset_builder_color.py to debug and try again.
