### ISSUE TITLE
3D Grid Generator and differentiability

### ISSUE THREAD

**Issue by v-prgmr** [epiception/CalibNet#25]
Greetings,

I was going through your paper. I would like to know about the 3D Grid Generator. You mention in the paper that the 3D point cloud projection to 2D space is carried out **differentiably**. 

Could someone point out where I can look for this portion in the code? 

Thank you

**Comment by oishigyunyu** [comment]
you mean that how to generate 3D point from 2D space?
if so, I think it's in code/common/all_transformer.py _3D_meshgrid_batchwise_diff

**Comment by v-prgmr** [comment]
@oishigyunyu, thank you (y)
