### ISSUE TITLE
about dataset_build_color.py and dataset_build_color_2.py

### ISSUE THREAD

**Issue by YingjianLiu** [epiception/CalibNet#4]
hi
  i want to know what method about 3d points clouds convert to 2d depth?
  how different about dataset_build_color.py and dataset_build_color_2.py, and why create two files?
  
 thank you very much!

**Comment by YingjianLiu** [comment]
and  in dataset_build_color.py this  file,  what means about R_rect_00 and cam_02_transform?

**Comment by epiception** [comment]
1. Dataset was built using projecting the lidar point cloud to the camera plane. Check any one of the scripts for more details. Two files were just for variability, they both have different rotation and translation limits from which the transforms are sampled, other than that both the files are basically the same.

2. cam_02_transform is for transformation to the camera 2 frame. R_rect_00 is a rectification transform. Both are available in the Kitti Calibration file.

Cheers!
