### ISSUE TITLE
velo_to_cam Matrix is necessary ?

### ISSUE THREAD

**Issue by AI-liu** [epiception/CalibNet#5]
dataset_build_color.py 
velo_to_cam = np.vstack((np.hstack((velo_to_cam_R, velo_to_cam_T)), np.array([[0,0,0,1]])))

velo_to_cam Matrix  is calibration result?
Is it necessary ?

Thanks!

**Comment by epiception** [comment]
For the ground truth generation, yes. But its never explicitly provided to the network during training to supervise upon.

**Comment by oaix** [comment]
> For the ground truth generation, yes. But its never explicitly provided to the network during training to supervise upon. @epiception 
If we get the ground truth of calibration result, it's unnecessary to train this network. The ground truth is what we need.
